### ISSUE TITLE
incompatibilities with node 0.12

### ISSUE THREAD

**Issue by cvlmtg** [C2FO/comb-proxy#9]
it seems this module is crashing when installed with node 0.12.1. the crash doesn't happen on install, but when I run my program which requires patio. there's no such crash under node 0.10.36.

Error: Cyclic __proto__ value
  at [object Object].__proto__ (native)
  at Object.set (/Users/matteo/dev/the-project/node_modules/patio/node_modules/comb-proxy/lib/proxy.js:59:23)
  at Object.set (/Users/matteo/dev/the-project/node_modules/patio/node_modules/comb-proxy/lib/proxy.js:59:23)
  at virtualRow (/Users/matteo/dev/the-project/node_modules/patio/lib/sql.js:51:22)
  at Object.<anonymous> (/Users/matteo/dev/the-project/node_modules/patio/lib/sql.js:535:12)
  at Object.get (/Users/matteo/dev/the-project/node_modules/patio/node_modules/comb-proxy/lib/proxy.js:79:52)
  at Object.<anonymous> (/Users/matteo/dev/the-project/node_modules/patio/lib/dataset/sql.js:1638:35)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/matteo/dev/the-project/node_modules/patio/lib/dataset/index.js:22:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/matteo/dev/the-project/node_modules/patio/lib/index.js:25:15)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/matteo/dev/the-project/node_modules/patio/index.js:1:90)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/matteo/dev/the-project/auction/helpers/loader.coffee:2:11)
  at Object.<anonymous> (/Users/matteo/dev/the-project/auction/helpers/loader.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/matteo/.nvf/installed/0.12.1/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/matteo/dev/the-project/auction/server.coffee:3:10)
  at Object.<anonymous> (/Users/matteo/dev/the-project/auction/server.coffee:1:1)
  at Module._compile (module.js:460:26)

**Comment by dustinsmith1024** [comment]
Hi @cvlmtg - we just release a version that will work with Node 4 or 5.  Can you use the newer versions of node or do you need it to work on 0.12?

**Comment by cvlmtg** [comment]
Hi, unfortunately the project where I used patio is dead :) anyway thanks for the update
